#!/usr/bin/env python
import sys
import argparse
import os
import shutil
import sync
import synchost


class Application:
    CONFIG_FILE = ".webpush.conf"
    HASH_DIR = ".webpush"

    def run(self):
        if self.args.host:
            self.host.parse(self.args.host)
        else:
            self.host.load(Application.CONFIG_FILE)

        if self.args.keyfile:
            self.host.keyfile = self.args.keyfile

        if self.args.clear:
            if os.path.isdir(self.HASH_DIR):
                shutil.rmtree(self.HASH_DIR)

        if self.args.init:
            self.host.save(Application.CONFIG_FILE)

        if self.args.sync:
            sync.SyncFolder(self).run()

    def __init__(self):
        p = argparse.ArgumentParser(
            description="Synchronize files and folders with a remote server (FTP, FTPS, SFTP).")
        p.add_argument("--init", action="store_true",
                       help="Initialize configuration. Requires the --host option.")
        p.add_argument("--sync", action="store_true",
                       help="Perform synchronization of tree. If no config has been written using the --init option you must specify the --host option.")
        p.add_argument("--host", action="store",
                       help="The URL of the host to synchronize with. If this option is given with init a config file is written so that the --sync option " +
                            "may be used without the --host option.")
        p.add_argument("--keyfile", action="store",
                       help="Optional private key file to use with SFTP.")
        p.add_argument("--clear", action="store_true",
                       help="Removes the hash directory and causes the whole tree to be re-synced.")

        self.args = p.parse_args()
        self.host = synchost.SyncHost()

if __name__ == "__main__":
    try:
        app = Application()
        app.run()
    except Exception as ex:
        print(ex)
        sys.exit(1)